main:
  path: /
  controller: App\Controller\ContentController::buildMain

account:
  path: /account
  controller: App\Controller\ContentController::buildAccount

deal:
  path: /deal
  controller: App\Controller\ContentController::buildDeal

reward:
  path: /reward
  controller: App\Controller\ContentController::buildReward